### ISSUE TITLE
An issue with the ruby gems solution

### ISSUE THREAD

**Issue by feilipu** [Arduino-CI/action#15]
I've revised the workflow file, and there is a[ new issue with the ruby gems solution](https://github.com/feilipu/Arduino_FreeRTOS_Library/runs/1672297520?check_suite_focus=true).

Now using `Arduino-CI/action@latest`.

Not sure if this is transient, or something more important.

```
Beginning the next phase of testing...           Compilation of example sketches

Discovered example sketch...                          AnalogRead_DigitalRead.ino
Default config, platforms matching architectures in library.properties... 
    uno
    leonardo
    trinket
    gemma
    mega2560
    cplayClassic
...Default config, platforms matching architectures in library.properties       
Board package arduino:avr has a defined URL...                                 ✓
Installing board package arduino:avr...                                        ✓
Board package adafruit:avr has a defined URL...                                ✓
Installing board package adafruit:avr...                                       ✓
bundler: failed to load command: /action/bundle/ruby/2.6.0/bin/arduino_ci.rb (/action/bundle/ruby/2.6.0/bin/arduino_ci.rb)
NoMethodError: undefined method `[]' for nil:NilClass
```

_Originally posted by @feilipu in https://github.com/Arduino-CI/action/issues/11#issuecomment-757086510_

**Comment by ianfixes** [comment]
Hi feilipu and thanks for opening this. I'm sorry again that you are running into this issue.  I'll try to fork your project and see what I can learn by testing it locally.

**Comment by ianfixes** [comment]
I found the issue... a subtle tweak at the last minute to satisfy my style checker introduced a subtle bug.

In the future I will have to break the test script into smaller more testable components, but for now the fix is in the master branch -- which `Arduino-CI/action@latest` pulls from.

I'll close this when the new released version of the action is available.

**Comment by feilipu** [comment]
I'll note that the blank `env:` doesn't work.
Was going to note that previously, but... didn't.

```
The workflow is not valid. .github/workflows/arduino_ci.yml (Line: 13, Col: 13): Unexpected value ''
```

**Comment by ianfixes** [comment]
Makes sense.  I should add a note that you must delete `env:` entirely if it's empty.  Do you think it would make the documentation more helpful (vs less) if I uncommented some of the default values in there?

**Comment by feilipu** [comment]
Just a note to comment out if not needed is necessary.

**Comment by ianfixes** [comment]
Sounds good, I've pushed an update to the docs on the master branch
