### ISSUE TITLE
CUSTOM_INIT_SCRIPT does not run script (or script fails without warning)

### ISSUE THREAD

**Issue by s-t-a-n** [Arduino-CI/action#19]
Hi there!

I have the following initscript: 

    #!/bin/sh

    # pull in Structures repo
    git clone https://github.com/s-t-a-n/Structures.git s-t-a-n--Structures

And in the Github CI I can see the CUSTOM_INIT_SCRIPT environment variable set, but I see no output whatsoever of it running (and therefore the tests always fail).

I have already tried adding 'apt-get install -y git' in the script, but that doesnt seem to help.

It always comes back with the following output:

    Located arduino-cli binary...                         /usr/local/bin/arduino-cli
    Installing library under test...                                               ✓
    WARNING... Installed library named 'Spine--Sensors' has directory name 'workspace'
    Library installed at...            /github/home/Arduino/libraries/Spine--Sensors
    Installing dependency of <library.properties>: 's-t-a-n--Structures'...        ✗
    This may indicate a problem with ArduinoCI, or your configuration
    Failures: 1
    Last message:  $  /usr/local/bin/arduino-cli --format json lib install --no-deps s-t-a-n--Structures
    ========== Stdout:
    
    ========== Stderr:
    Error installing name:"s-t-a-n--Structures": looking for library: library s-t-a-n--Structures not found

Running on a local machine with 'export CUSTOM_INIT_SCRIPT=....' install the library properly. 

Our repo is residing @ https://github.com/autonomousrobotshq/Spine--Sensors if you want to have a look yourself.

I am pulling my hairs out as to what is going wrong. Any help is appreciated! As is the effort for setting up this CI suite in the first place!

gr Stan

**Comment by s-t-a-n** [comment]
I'm an idiot, officially now haha. I completely overlooked the version of the github action I was using. It was fixed at version 0.1.0 because I was using the Arduino-CI/Blink example action together with the environment variables set in Arduino-CI/action. I put in a pull request for Arduino-CI/Blink at your discretion. Sorry for bothering you so soon. Thanks a bunch for this all work on this awesome framework!

**Comment by ianfixes** [comment]
😅 No bother, thanks for getting in touch!  `@stable-1.x` is a relatively new feature that I'm working with -- I think best practices for GitHub actions are still being discovered.  

I appreciate the kind words, and please don't hesitate to open issues for things you encounter in the future; many times they point to rough edges in the software or the documentation.
